print("**************")
print("HESAP MAKİNESİ")
print("**************")
print("1-Toplama")
print("2-Çıkarma")
print("3-Çarpma")
print("4-Bölme")
print("5-Çıkış")
islem=input=print("işlem seçiniz(1-5):")
